### ISSUE TITLE
as I shoot the -

### ISSUE THREAD

**Issue by shyricaus** [jonassvensson4/jsfour-legitimation#2]
Thanks, I've already been able to solve it, so I'm having another problem. with the date being appearing (-) where it was to appear numbers

![image](https://user-images.githubusercontent.com/28937245/46920230-7f872080-cfc1-11e8-8507-420f6ad47ed3.png)

**Comment by shyricaus** [comment]
my date system and brazil, the case and deferente of europe.

![image](https://user-images.githubusercontent.com/28937245/46920546-3be2e580-cfc6-11e8-80b9-50d64f017ff0.png)

**Comment by shyricaus** [comment]
from what I'm seeing and in this line var pNumb = data.dateofbirth.substring (2,4) + data.dateofbirth.substring (5,7) + data.dateofbirth.substring (8,10) ;. in jsfour-legitimation \ html \ assets \ js \ init.js ... could I give a hint as I leave it to my country

**Comment by jnsvns** [comment]
It's not a date. It's your date of birth. The reason you're getting that is because you have a diffrent format. If everyone gets their DOB in the same format as you do you can use this

var pNumb =  data.dateofbirth.substring(0,2) + data.dateofbirth.substring(3,5) + data.dateofbirth.substring(8,10);
